language: c

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make
#  - ./turbob64 turbob64c.c

matrix:
  include:
    - name: Linux arm gcc
      os: linux
      arch: arm64
      compiler: gcc

    - name: Linux arm clang
      os: linux
      arch: arm64
      compiler: clang

    - name: Windows-MinGW
      os: windows
      script: 
        - mingw32-make
#       - ./tb64app turbob64c.c

    - name: macOS, xcode
      os: osx

#    - name: Linux amd64
#      os: linux
#      arch: amd64
#    - name: Power ppc64le
#      os: linux-ppc64le
#      compiler: gcc     

