language: c

dist: bionic

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make
  - gcc -v
  - clang -v
  - ./tb64app turbob64c.c

matrix:
  include:
    - name: Linux-ppc64le-gcc-8
      env: CC=gcc-8
      os: linux
      arch: ppc64le
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -y update
        - sudo apt-get -y install gcc-8

    - name: Linux-Arm64-clang-7
#      dist: bionic 
#      os: linux
       arch: aarch64
#      addons:
#        apt:
#          update: true
#          sources: *apt_sources
#          packages: [*apt_packages, 'clang-6']
       env: CC=clang-7

    - name: Windows-MinGW
      arch: amd64 
      os: windows
      script: 
        - mingw32-make
#        - ./tb64app turbob64c.c

    - name: macOS, xcode
      os: osx


