language: c

arch:
#  - amd64
#  - arm64
#  - s390x
#  - ppc64le only gcc>=8.0

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make
  - gcc -v
  - clang -v
  - ./tb64app turbob64c.c

matrix:
  include:
    - name: linux-arm64-clang-7
      dist: bionic 
      os: linux
      arch: arm64
      addons:
        apt:
          update: true
          sources: *apt_sources
          packages: [*apt_packages, 'clang-7']
      env: CC=clang-7
      script:
        - make
        - clang-7 -v
        - clang-7 -O3 -S -march=armv8-a turbob64sse.c
        - cat turbob64sse.s
        - ./tb64app turbob64c.c

    - name: linux-ppc64le-gcc-9
      env: CC=gcc-9
      os: linux
      arch: ppc64le
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -y update
        - sudo apt-get -y install gcc-9

    - name: Windows-MinGW
      arch: amd64 
      os: windows
      script: 
        - mingw32-make
        - ./tb64app turbob64c.c

    - name: macOS, xcode
      os: osx


