language: c

arch:
  - amd64
  - arm64
#  - ppc64le >=gcc-8
  - s390x

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
# cd src
  - make
  - ./tb64app turbob64c.c

matrix:
  include:
    - name: Linux-ppc64le-gcc-9
      env: CC=gcc-9
      os: linux
      arch: ppc64le
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -y update
        - sudo apt-get -y install gcc-9

    - name: Linux-Arm64-clang-7
#      distr: bionic 
#      os: linux
      arch: arm64
#      addons:
#        apt:
#          update: true
#          sources: *apt_sources
#          packages: [*apt_packages, 'clang-6']
      env: CC=clang-7

    - name: Windows-MinGW
      arch: amd64 
      os: windows
      script: 
        - mingw32-make
#        - ./tb64app turbob64c.c

    - name: macOS, xcode
      os: osx


