language: c

arch:
  - amd64
  - arm64
  - s390x

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make

matrix:
  include:
    - name: linux-ppc64le-gcc-9
      env: CC=gcc-9
      os: linux
      arch: ppc64le
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -y update
        - sudo apt-get -y install gcc-9

    - name: Windows-MinGW
      arch: amd64 
      os: windows
      script: 
        - mingw32-make

    - name: macOS, xcode
      os: osx


